sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GWHs5TGVc9thUSXFkFiLaLmIVAC3kWjs02j3fY0s8VaX6WPb4YNBxSHEHT1G9VwTLjbWuKtoZEdiS1K70/VFv3ZVQay8LHXW0i7hsiZxb8DmvhnvGEYN72uYAF+xk/o/o65E6bEuKMGsid0YqQ5Ff0QhqWhCeUGj4YWKQ+D/78VgOclooQUdXW0roGsxQ26K1pOsk3B6J4OwUqoQlBUvqj5X2XpGUAiRZCYDhiQ6islJmeZbuFN7Zn9O5tKT8bQZg8B0rLzfMqiA98qxCkb1GNIibzopFt+MjyqGXr7M3w1F0he0l39hUd/YVfFjAIPTygzUOaGcq2mpJMCWtJniSHJki8sXk3P8Qd6M/YQ7PbdEetpBFVIr7fPuKNJjGJsW9Y09FyLT/8B0soJkdW8/GGwMMCbBoJcKB+71QIfc7W8iCSfTxh/9S7ZlICbMh+mbN8LOirIxx9hDFUIBXKoNOuupzkjj9UnKbNwHhFMO1E73olizq2mpTO/IuB+alFf7DPTArtDObQZc5gYed78clhs6lRbGf4vRLr9EuYWfoNrjwSUnWPYkfRjLE/zTW0X7rS0/c3+IkHY2kbjs/XFuDaJNFPo/RSx6Ak8++x0vaHBgc1mOJ783HVD+EPt9Ralxg8u5WBnYQSVjxWAdcRtIqseMI6S8T97pslG0xs20pSk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Their-Silver-Wedding-Journey---Volume-2_3372
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy